### ISSUE TITLE
Samsung

### ISSUE THREAD

**Issue by danielducu** [johnboiles/esphome-hdmi-cec#1]
Not working on Samsung (Anynet+)

**Comment by johnboiles** [comment]
More details please (what chip / dev board).

Also enable promiscuous_mode and post the logs.

**Comment by danielducu** [comment]
> More details please (what chip / dev board).
> 
> Also enable promiscuous_mode and post the logs.

**Comment by nagyrobi** [comment]
I also have issues with Samsung.
Promiscuous mode enabled, all I get is:
```
[18:21:12][D][hdmi_cec:145]: Ran 82778 times in 10000ms (every 0.120805ms)
[18:21:22][D][hdmi_cec:145]: Ran 56314 times in 10000ms (every 0.177576ms)
[18:21:32][D][hdmi_cec:145]: Ran 56248 times in 10000ms (every 0.177784ms)
[18:21:42][D][hdmi_cec:145]: Ran 56199 times in 10000ms (every 0.177939ms)
[18:21:52][D][hdmi_cec:145]: Ran 56111 times in 10000ms (every 0.178218ms)

```

Other symptom is if I connect the node to the TV while it's powered off, it cannot be turned on. Screen flashes in a kind of a bootloop. As soon as I remove connection from HDMI pin 18, the TV boots successfully. 

After that I can reconnect HDMI pin 18 to Wemos D1 Mini's 5V, Samsung will detect an unknown source on the HDMI port. Unfortunately no HDMI ARC audio output will be shown in the menus.

Another symptom is that the Wemos can't be flashed via OTA while the HDMI cable is plugged in. It will fail with `ERROR Error sending data: [Errno 104] Connection reset by peer`. If I unplug the HDMI cable, OTA works fine.

The TV is a Samsung UE50AU7102.

**Comment by nagyrobi** [comment]
OK seems like this is a grounding issue when powered from external DC5V charger. Connection issues go away if I power the ESP from the USB port of the TV. Which is problematic because when I turn off the TV the ESP goes off too...
